
#[web_servers]
#54.83.68.184  ansible_user=ec2-user
#[web_servers]
#3.91.71.176
[all]
54.226.26.92
34.228.20.143

[all:vars]

#ansible_ssh_common_args='-F /home/siham/.ssh/config'
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
